import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "~/components/ui/sonner";
import Header from "~/components/header";
import Footer from "~/components/footer";

//  Define Inter font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Event Management System",
  description: "Generated by Md. Ruhul Amin. Full Stack developer Specialize on MERN.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-sans`}
      >
        <Header />
        {children}
        <Toaster richColors />
        <Footer />
      </body>
    </html>
  );
}